imports:
    - { resource: tables.yml }
    - { resource: portal_services.yml }

# mapping of services to controller classes
services:
    avathar.bbguild.controller:
        class: avathar\bbguild\controller\view_controller
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@pagination'
            - '@path_helper'
            - '@template'
            - '@request'
            - '@user'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
            - '@avathar.bbguild.game_registry'
            - '@avathar.bbguild.portal.renderer'
    avathar.bbguild.admin.controller:
        class: avathar\bbguild\controller\admin_controller_temp
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
    avathar.bbguild.curl:
        class: avathar\bbguild\model\admin\curl
    avathar.bbguild.log:
        # bbguild logging class
        class: avathar\bbguild\model\admin\log
        arguments:
            - '%avathar.bbguild.tables.bb_logs%'
            - '@dbal.conn'
            - '@user'
    avathar.bbguild.util:
        class: avathar\bbguild\model\admin\util
        arguments:
            - '@request'
    avathar.bbguild.admin.main:
        class: avathar\bbguild\controller\admin_main
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '@dispatcher'
            - '@avathar.bbguild.curl'
            - '@avathar.bbguild.log'
            - '@avathar.bbguild.util'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
    avathar.bbguild.admin.games:
        class: avathar\bbguild\controller\admin_games
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '@avathar.bbguild.curl'
            - '@avathar.bbguild.log'
            - '@avathar.bbguild.util'
            - '@avathar.bbguild.game_registry'
            - '@dispatcher'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
    avathar.bbguild.admin.guild:
        class: avathar\bbguild\controller\admin_guild
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@path_helper'
            - '@ext.manager'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '@avathar.bbguild.curl'
            - '@avathar.bbguild.log'
            - '@avathar.bbguild.util'
            - '@controller.helper'
            - '@avathar.bbguild.game_registry'
            - '@dispatcher'
            - '@avathar.bbguild.portal.modules.database_handler'
            - '@avathar.bbguild.admin.portal'
            - '%avathar.bbguild.tables.bb_games%'
            - '%avathar.bbguild.tables.bb_logs%'
            - '%avathar.bbguild.tables.bb_ranks%'
            - '%avathar.bbguild.tables.bb_guild%'
            - '%avathar.bbguild.tables.bb_players%'
            - '%avathar.bbguild.tables.bb_classes%'
            - '%avathar.bbguild.tables.bb_races%'
            - '%avathar.bbguild.tables.bb_gameroles%'
            - '%avathar.bbguild.tables.bb_factions%'
            - '%avathar.bbguild.tables.bb_language%'
            - '%avathar.bbguild.tables.bb_motd%'
            - '%avathar.bbguild.tables.bb_recruit%'
            - '%avathar.bbguild.tables.bb_bosstable%'
            - '%avathar.bbguild.tables.bb_zonetable%'
            - '%avathar.bbguild.tables.bb_news%'
    avathar.bbguild.admin.portal:
        class: avathar\bbguild\controller\admin_portal
        arguments:
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@avathar.bbguild.portal.columns'
            - '@avathar.bbguild.portal.module_registry'
            - '@avathar.bbguild.portal.modules.database_handler'
            - '@avathar.bbguild.portal.modules.manager'
            - '@avathar.bbguild.portal.config'
            - '%avathar.bbguild.tables.bb_guild%'
    avathar.bbguild.game_provider_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: bbguild.game_provider }
    avathar.bbguild.game_registry:
        class: avathar\bbguild\model\games\game_registry
        arguments:
            - '@avathar.bbguild.game_provider_collection'
    avathar.bbguild.listener:
        class: avathar\bbguild\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@config'
            - '@dbal.conn'
            - '%avathar.bbguild.tables.bb_guild%'
        tags:
            - { name: event.listener }
