parameters:
    avathar.bbguild.tables.bb_games: '%core.table_prefix%bb_games'
    avathar.bbguild.tables.bb_logs: '%core.table_prefix%bb_logs'
    avathar.bbguild.tables.bb_ranks: '%core.table_prefix%bb_ranks'
    avathar.bbguild.tables.bb_guild: '%core.table_prefix%bb_guild'
    avathar.bbguild.tables.bb_players: '%core.table_prefix%bb_players'
    avathar.bbguild.tables.bb_classes: '%core.table_prefix%bb_classes'
    avathar.bbguild.tables.bb_races: '%core.table_prefix%bb_races'
    avathar.bbguild.tables.bb_gameroles: '%core.table_prefix%bb_gameroles'
    avathar.bbguild.tables.bb_factions: '%core.table_prefix%bb_factions'
    avathar.bbguild.tables.bb_language: '%core.table_prefix%bb_language'
    avathar.bbguild.tables.bb_motd: '%core.table_prefix%bb_motd'
    avathar.bbguild.tables.bb_recruit: '%core.table_prefix%bb_recruit'
    avathar.bbguild.tables.bb_bosstable: '%core.table_prefix%bb_bosstable'
    avathar.bbguild.tables.bb_zonetable: '%core.table_prefix%bb_zonetable'
    avathar.bbguild.tables.bb_news: '%core.table_prefix%bb_news'
    avathar.bbguild.tables.bb_portal_modules: '%core.table_prefix%bb_portal_modules'
    avathar.bbguild.tables.bb_portal_config: '%core.table_prefix%bb_portal_config'